### ISSUE TITLE
Website down D:

### ISSUE THREAD

**Issue by cog25** [MinSeungHyun/implude-web#7]
![implude com_](https://user-images.githubusercontent.com/74242561/106704832-19aa8100-6630-11eb-8df4-280b6bdb70e7.png)

**Comment by MinSeungHyun** [comment]
서버에 문제가 생겨서 죽어버렸습니다.. 빠른 시일 내로 복구해서 여기에 코멘트 남길게요!
일단 2800d66bc82c889350e3fdad0cd664f2aa9fcbd1 커밋까지 반영된 버전은 [implude-web.vercel.app](https://implude-web.vercel.app)에서 보실 수 있어요

**Comment by MinSeungHyun** [comment]
[implude.com](https://implude.com)에 배포 되었습니다!
